/**
 * ESLint flat config. `eslint-config-next` still ships eslintrc-shaped configs
 * (no `exports` map, no flat entry point as of 15.5), so FlatCompat translates
 * them rather than us hand-rolling the Next plugin wiring.
 *
 * `prettier` goes last on purpose: it turns off the stylistic rules Prettier
 * already owns, so `pnpm lint` and `pnpm format:check` cannot contradict.
 */

import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      // Generated by drizzle-kit; not ours to lint or format.
      'src/lib/db/migrations/**',
      // Agent worktrees and session state. Untracked, and a checked-out
      // worktree here would otherwise get linted as a second copy of the repo.
      '.claude/**',
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),
  {
    // Tool configs are consumed by their tool's default import, not by us.
    files: ['*.config.mjs', '*.config.ts'],
    rules: { 'import/no-anonymous-default-export': 'off' },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
];
